using Microsoft.CodeAnalysis;
using System.Text;

namespace CollectionGenerator;

[Generator]
public sealed class AddToGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext Context) {
        IncrementalValuesProvider<AddToCollectionInfo> AddToCollectionInfos = Context.SyntaxProvider
            .ForAttributeWithMetadataName($"{nameof(CollectionGenerator)}.{nameof(AddToAttribute)}",
                static (Node, CancellationToken) => true,
                static (Context, CancellationToken) => {
                    ISymbol? FieldOrProperty = Context.TargetSymbol;
                    if (FieldOrProperty is not (IFieldSymbol or IPropertySymbol)) {
                        return null;
                    }

                    List<string>? TargetArrays = null;

                    foreach (AttributeData Attribute in FieldOrProperty.GetAttributes()) {
                        if (Attribute.AttributeClass is null) {
                            continue;
                        }
                        if (Attribute.AttributeClass.ToDisplayString() is not $"{nameof(CollectionGenerator)}.{nameof(AddToAttribute)}") {
                            continue;
                        }

                        foreach (TypedConstant Argument in Attribute.ConstructorArguments) {
                            foreach (TypedConstant Value in Argument.Values) {
                                if (Value.Value is not string TargetArray) {
                                    continue;
                                }

                                TargetArrays ??= [];
                                TargetArrays.Add(TargetArray);
                            }
                        }
                    }

                    if (TargetArrays is null) {
                        return null;
                    }

                    return new AddToCollectionInfo(FieldOrProperty, TargetArrays);
                })
            .Where(static (AddToCollectionInfo) => AddToCollectionInfo is not null)
            .Select(static (AddToCollectionInfo, CancellationToken) => AddToCollectionInfo!);

        Context.RegisterSourceOutput(
            AddToCollectionInfos.Collect(),
            static (Context, AddToCollectionInfos) => {
                foreach (IGrouping<ISymbol?, AddToCollectionInfo> Group in AddToCollectionInfos.GroupBy(AddToCollectionInfo => AddToCollectionInfo.FieldOrProperty.ContainingType, SymbolEqualityComparer.Default)) {
                    if (Group.Key is not INamedTypeSymbol Type) {
                        continue;
                    }
                    Generate(Context, Type, Group);
                }
            });
    }

    private static void Generate(SourceProductionContext Context, INamedTypeSymbol Type, IEnumerable<AddToCollectionInfo> AddToCollectionInfos) {
        IEnumerable<IGrouping<string, (string ArrayName, string FieldOrPropertyName)>> Groups = AddToCollectionInfos
            .SelectMany(AddToCollectionInfo => AddToCollectionInfo.TargetArrays.Select(Name => (Name, AddToCollectionInfo.FieldOrProperty.Name)))
            .GroupBy(Entry => Entry.Item1);

        StringBuilder StringBuilder = new();

        StringBuilder.AppendLine("// <auto-generated />");
        StringBuilder.AppendLine();
        StringBuilder.AppendLine("#nullable enable");
        StringBuilder.AppendLine();

        if (!Type.ContainingNamespace.IsGlobalNamespace) {
            StringBuilder.Append("namespace ");
            StringBuilder.Append(Type.ContainingNamespace.ToDisplayString());
            StringBuilder.AppendLine(";");
            StringBuilder.AppendLine();
        }

        StringBuilder.Append("partial ");
        if (Type.IsRecord) {
            StringBuilder.Append("record ");
        }
        StringBuilder.Append(Type.IsValueType ? "struct " : "class ");
        StringBuilder.Append(Type.Name);
        StringBuilder.AppendLine(" {");

        StringBuilder.Append("    static ");
        StringBuilder.Append(Type.Name);
        StringBuilder.AppendLine("() {");

        foreach (IGrouping<string, (string ArrayName, string FieldOrPropertyName)> Group in Groups) {
            StringBuilder.Append("        ");
            StringBuilder.Append(Group.Key);
            StringBuilder.AppendLine(" = [");

            foreach ((string ArrayName, string FieldOrPropertyName) in Group) {
                StringBuilder.Append("            ");
                StringBuilder.Append(FieldOrPropertyName);
                StringBuilder.AppendLine(",");
            }

            StringBuilder.AppendLine("        ];");
        }

        StringBuilder.AppendLine("    }");
        StringBuilder.AppendLine("}");

        Context.AddSource($"{Type.Name}.AddToCollection.g.cs", StringBuilder.ToString());
    }

    private sealed record AddToCollectionInfo(ISymbol FieldOrProperty, List<string> TargetArrays);
}