using Microsoft.CodeAnalysis;
using System.Text;

namespace CollectionGenerator;

[Generator]
public sealed class AddToGenerator : IIncrementalGenerator {
    public void Initialize(IncrementalGeneratorInitializationContext Context) {
        IncrementalValuesProvider<AddToInfo> AddToInfos = Context.SyntaxProvider
            .ForAttributeWithMetadataName("CollectionGenerator.AddToAttribute",
                static (Node, CancellationToken) => true,
                static (Context, CancellationToken) => {
                    ISymbol? FieldOrProperty = Context.TargetSymbol;
                    if (FieldOrProperty is not (IFieldSymbol or IPropertySymbol)) {
                        return null;
                    }

                    List<string>? TargetArrays = null;

                    foreach (AttributeData Attribute in FieldOrProperty.GetAttributes()) {
                        if (Attribute.AttributeClass is null) {
                            continue;
                        }
                        if (Attribute.AttributeClass.ToDisplayString() is not "CollectionGenerator.AddToAttribute") {
                            continue;
                        }

                        foreach (TypedConstant Argument in Attribute.ConstructorArguments) {
                            foreach (TypedConstant Value in Argument.Values) {
                                if (Value.Value is not string TargetArray) {
                                    continue;
                                }

                                TargetArrays ??= [];
                                TargetArrays.Add(TargetArray);
                            }
                        }
                    }

                    if (TargetArrays is null) {
                        return null;
                    }

                    return (AddToInfo?)new AddToInfo(FieldOrProperty, TargetArrays);
                })
            .Where(static (AddToInfo) => AddToInfo is not null)
            .Select(static (AddToInfo, CancellationToken) => AddToInfo!.Value);

        Context.RegisterPostInitializationOutput(
            GenerateAttribute
        );

        Context.RegisterSourceOutput(
            AddToInfos.Collect(),
            static (Context, AddToInfos) => {
                foreach (IGrouping<ISymbol?, AddToInfo> Group in AddToInfos.GroupBy(AddToInfo => AddToInfo.FieldOrProperty.ContainingType, SymbolEqualityComparer.Default)) {
                    if (Group.Key is not INamedTypeSymbol Type) {
                        continue;
                    }
                    GenerateStaticConstructor(Context, Type, Group);
                }
            });
    }

    private static void GenerateAttribute(IncrementalGeneratorPostInitializationContext Context) {
        Context.AddSource("AddToAttribute.g.cs", """
            // <auto-generated />

            #nullable enable

            namespace CollectionGenerator;

            [System.AttributeUsage(System.AttributeTargets.Field | System.AttributeTargets.Property, AllowMultiple = true, Inherited = false)]
            public sealed class AddToAttribute(params string[] ArrayNames) : System.Attribute {
                public string[] ArrayNames { get; } = ArrayNames;
            }

            """);
    }

    private static void GenerateStaticConstructor(SourceProductionContext Context, INamedTypeSymbol Type, IEnumerable<AddToInfo> AddToInfos) {
        IEnumerable<IGrouping<string, (string ArrayName, string FieldOrPropertyName)>> Groups = AddToInfos
            .SelectMany(AddToInfo => AddToInfo.TargetArrays.Select(Name => (Name, AddToInfo.FieldOrProperty.Name)))
            .GroupBy(Entry => Entry.Item1);

        StringBuilder StringBuilder = new();

        StringBuilder.AppendLine("// <auto-generated />");
        StringBuilder.AppendLine();
        StringBuilder.AppendLine("#nullable enable");
        StringBuilder.AppendLine();

        if (!Type.ContainingNamespace.IsGlobalNamespace) {
            StringBuilder.Append("namespace ");
            StringBuilder.Append(Type.ContainingNamespace.ToDisplayString());
            StringBuilder.AppendLine(";");
            StringBuilder.AppendLine();
        }

        StringBuilder.Append("partial ");
        if (Type.IsRecord) {
            StringBuilder.Append("record ");
        }
        StringBuilder.Append(Type.IsValueType ? "struct " : "class ");
        StringBuilder.Append(Type.Name);
        StringBuilder.AppendLine(" {");

        StringBuilder.Append("    static ");
        StringBuilder.Append(Type.Name);
        StringBuilder.AppendLine("() {");

        foreach (IGrouping<string, (string ArrayName, string FieldOrPropertyName)> Group in Groups) {
            StringBuilder.Append("        ");
            StringBuilder.Append(Group.Key);
            StringBuilder.AppendLine(" = [");

            foreach ((string ArrayName, string FieldOrPropertyName) in Group) {
                StringBuilder.Append("            ");
                StringBuilder.Append(FieldOrPropertyName);
                StringBuilder.AppendLine(",");
            }

            StringBuilder.AppendLine("        ];");
        }

        StringBuilder.AppendLine("    }");
        StringBuilder.AppendLine("}");

        Context.AddSource($"{Type.Name}.AddTo.g.cs", StringBuilder.ToString());
    }

    private readonly record struct AddToInfo(ISymbol FieldOrProperty, List<string> TargetArrays);
}