<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <VersionPrefix>2.0</VersionPrefix>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <RootNamespace>CollectionGenerator</RootNamespace>
        <ImplicitUsings>true</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
        
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>

        <!-- When users install the package, adds PrivateAssets="true" by default -->
        <DevelopmentDependency>true</DevelopmentDependency>
    </PropertyGroup>

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>CollectionGenerator</Title>
        <Description>Generates collections from members in C#.</Description>
        <PackageProjectUrl>https://github.com/Joy-less/CollectionGenerator</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Joy-less/CollectionGenerator</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>collection; member; generator; AddToAttribute; AddTo</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../README.md">
            <Pack>true</Pack>
            <PackagePath>/</PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup>
        <!-- Must support oldest .NET 8.0 version (see https://github.com/dotnet/roslyn/blob/main/docs/wiki/NuGet-packages.md#versioning) -->
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" PrivateAssets="all" />

        <PackageReference Include="PolySharp" Version="1.16.0" PrivateAssets="all" />
    </ItemGroup>

    <!-- Store package in analyzer directory (https://stackoverflow.com/a/65010790) -->
    <ItemGroup>
        <None Include="$(OutputPath)/$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    </ItemGroup>
</Project>
